// Generated by CoffeeScript 1.6.2
(function() {
  var fs, _;

  fs = require('fs');

  _ = require('underscore');

  exports.store = function(file_id, meta, callback) {
    var _store_file;

    _store_file = './metadata/store.json';
    return fs.readFile(_store_file, function(err, data) {
      var e, _meta;

      if (err) {
        throw err;
      }
      if (data.length === 0) {
        _meta = {};
      } else {
        try {
          _meta = JSON.parse(data);
        } catch (_error) {
          e = _error;
          throw e;
        }
      }
      console.log(_meta);
      console.log(data.length);
      meta = _.extend(_meta, meta);
      console.log(meta);
      return fs.writeFile(_store_file, JSON.stringify(meta), function(err) {
        if (err) {
          throw err;
        } else {
          return callback(true);
        }
      });
    });
  };

}).call(this);
