// Generated by CoffeeScript 1.6.2
(function() {
  exports.uuid = function(a) {
    if (a) {
      return (a ^ Math.random() * 16 >> a / 4).toString(16);
    } else {
      return ([1e7] + 1e3 + 4e3 + 8e3 + 1e11).replace(/[018]/g, this.uuid);
    }
  };

  exports.mongo = function(callback) {
    var db, files, mongoq;

    mongoq = require("mongoq");
    db = mongoq("tus", {
      host: "127.0.0.1",
      port: "27017",
      w: 1
    });
    files = db.collection("files");
    return callback(files);
  };

}).call(this);
